### ISSUE TITLE
Issues with 'Enable' option still

### ISSUE THREAD

**Issue by msd-rjoachim** [iamtheyammer/gam-cros-win-wrapper#6]
I was hoping it would be that simple, but the problem is still here using the latest build.

Here's my workflow, in case it matters - 

- Type in serial number (for example)
- Click Submit
- Info box shows 'status: DISABLED'
- Click 'Enable'
- Info box shows "As long as you don't see an error, this query completed successfully."

I check in Google Admin and the device status hasn't changed. If I click 'Get Info', the status still shows as disabled. If I manually use GAM, it is enabled properly.

I noticed that you documented the enable command as 'gam update cros $deviceId reenable' - I believe this should be 'gam update cros $deviceId **action** reenable"?

**Comment by iamtheyammer** [comment]
I will fix this in the next release that I am working on right now. The issue is that I had written it originally as `gam update cros $deviceId enable`. Wrong. So, I changed it to `gam update cros $deviceId action enable`, which is in the current version. Still wrong. Updating it now to say `gam update cros $deviceId action reenable`, which should fix it.

This is completely an ID10T error, sorry about that!

**Comment by msd-rjoachim** [comment]
Sounds great.

One other item I noticed regarding the output. Currently - 
`gamResult += "\nAs long as you don't see an error, this query completed successfully."`

Should it be - 
`gamResult + "\nAs long as you don't see an error, this query completed successfully."`?
